In [1]:
import matplotlib.pyplot as plt
import pandas as pd

dfA = pd.read_csv('out/collection_280421.csv')
dfB = pd.read_csv('out/collection_030621.csv')

dfA['id'].count(), dfB['id'].count()

(241, 245)

In [2]:
df = pd.merge(dfA, dfB, how='inner', on=['id', 'title', 'url'])
df = df[(df['last_sold_x'] != 0) & (df['last_sold_y'] != 0)]

In [3]:
view = ['id','title', 'med_x', 'med_y', 'url', 'for_sale_x', 'for_sale_y']
df.query('start_x==0 | start_y==0')[view]

,id,title,med_x,med_y,url,for_sale_x,for_sale_y
50,711062,b'Phat Beats 194',3.94,3.97,https://www.discogs.com/release/711062,0,0
124,12695505,b'Zero Waste',0.00,0.00,https://www.discogs.com/release/12695505,0,0
125,175932,b'Star 69 (What The F**k)',4.99,4.95,https://www.discogs.com/release/175932,0,0
141,12066554,b'Heat',14.07,13.93,https://www.discogs.com/release/12066554,0,0
192,15202114,b'The Very Polish Cut-Outs Vol. 0',30.00,30.00,https://www.discogs.com/release/15202114,0,0

In [4]:
df['med_diff'] = df['med_y'] - df['med_x']
df['med_diff'].describe()

count    241.000000
mean       0.305934
std        2.798897
min       -4.670000
25%       -0.010000
50%        0.000000
75%        0.060000
max       40.270000
Name: med_diff, dtype: float64

In [5]:
view = ['id','title', 'med_x', 'med_y', 'url', 'for_sale_x', 'for_sale_y']
df.sort_values(by='med_diff', ascending=True)[view].head(10)

,id,title,med_x,med_y,url,for_sale_x,for_sale_y
41,1058605,b'All Eyez On Me',29.05,24.38,https://www.discogs.com/release/1058605,64,39
70,9134,b'Life Is Sweet',10.14,6.93,https://www.discogs.com/release/9134,47,50
234,20688,b'Smack My Bitch Up',15.00,12.70,https://www.discogs.com/release/20688,42,42
107,144183,"b""Freek'n You""",11.53,9.37,https://www.discogs.com/release/144183,30,31
123,1508621,b'Tical 2000 Instrumental LP',12.00,10.00,https://www.discogs.com/release/1508621,7,6
217,158717,"b""Burnin'""",13.45,11.51,https://www.discogs.com/release/158717,4,7
237,11524,b'Out Of Space',17.29,16.11,https://www.discogs.com/release/11524,44,45
106,14251562,b'Pulp Fiction: Music From The Motion Picture',26.52,25.40,https://www.discogs.com/release/14251562,24,21
66,67138,b'The Saint',3.27,2.30,https://www.discogs.com/release/67138,57,60
165,351364,b'Les Nocturnes',3.25,2.33,https://www.discogs.com/release/351364,44,43

In [6]:
df['high_diff'] = df['high_y'] - df['high_x']
df['high_diff'].describe()

count    241.000000
mean      -0.032282
std        5.846735
min      -54.810000
25%        0.000000
50%        0.000000
75%        0.020000
max       34.030000
Name: high_diff, dtype: float64

In [7]:
view = ['id','title', 'high_x', 'high_y', 'url', 'for_sale_x', 'for_sale_y']
df.sort_values(by='high_diff', ascending=True)[view].head(10)

,id,title,high_x,high_y,url,for_sale_x,for_sale_y
5,6424917,b'Alive 2007',177.77,122.96,https://www.discogs.com/release/6424917,49,37
213,13861184,b'RTRN II JUNGLE',57.64,25.99,https://www.discogs.com/release/13861184,46,55
41,1058605,b'All Eyez On Me',99.99,69.69,https://www.discogs.com/release/1058605,64,39
187,1614916,b'Omen',19.99,6.90,https://www.discogs.com/release/1614916,30,29
12,12953039,b'Overpowered',45.65,35.95,https://www.discogs.com/release/12953039,39,31
147,189138,b'Watch Out Now',19.00,10.00,https://www.discogs.com/release/189138,86,80
228,5310465,b'Watermark',22.00,15.00,https://www.discogs.com/release/5310465,43,44
22,9438479,b'Protection',29.99,24.90,https://www.discogs.com/release/9438479,198,189
215,9442778,b'Blue Lines',33.18,28.88,https://www.discogs.com/release/9442778,279,273
234,20688,b'Smack My Bitch Up',22.62,18.48,https://www.discogs.com/release/20688,42,42

In [8]:
df['low_diff'] = df['low_y'] - df['low_x']

In [9]:
view = ['id','title', 'low_x', 'low_y', 'url', 'for_sale_x', 'for_sale_y']
df.sort_values(by='low_diff', ascending=False)[view].head(10)

,id,title,low_x,low_y,url,for_sale_x,for_sale_y
142,34228,b'Plastic Dreams (Mixes)',5.76,13.86,https://www.discogs.com/release/34228,25,24
211,135671,b'Homework / Discovery / Alive 1997',85.00,90.00,https://www.discogs.com/release/135671,12,11
202,2367912,b'She Knows You',30.00,34.85,https://www.discogs.com/release/2367912,2,3
62,3880279,b'Bad 25',12.00,16.17,https://www.discogs.com/release/3880279,26,23
231,1553943,b'The Fat Of The Land',15.00,18.00,https://www.discogs.com/release/1553943,32,29
222,112902,b'Darkdancer',10.00,12.71,https://www.discogs.com/release/112902,12,14
111,201872,b'Rocket Fuel',2.48,5.00,https://www.discogs.com/release/201872,15,15
30,3554,b'Quadrastate',6.00,8.20,https://www.discogs.com/release/3554,46,40
171,28002,b'Last Night A D.J. Saved My Life',3.00,4.99,https://www.discogs.com/release/28002,53,53
170,163921,b'Lady (Remixed)',3.99,5.74,https://www.discogs.com/release/163921,12,14

In [10]:
view = ['id','title', 'low_x', 'med_x', 'high_x', 'low_y', 'med_y', 'high_y', 'url', 'stat_sum']
df['stat_sum'] = df['low_diff'] + df['med_diff'] + df['high_diff']
df.sort_values(by='stat_sum', ascending=False)[view]

,id,title,low_x,med_x,high_x,low_y,med_y,high_y,url,stat_sum
211,135671,b'Homework / Discovery / Alive 1997',85.00,207.68,333.00,90.00,247.95,333.00,https://www.discogs.com/release/135671,45.27
171,28002,b'Last Night A D.J. Saved My Life',3.00,6.59,11.53,4.99,7.72,45.56,https://www.discogs.com/release/28002,37.15
142,34228,b'Plastic Dreams (Mixes)',5.76,14.42,20.75,13.86,15.79,34.64,https://www.discogs.com/release/34228,23.36
208,210723,b'The Killa-Hertz',0.01,5.19,9.22,0.01,6.99,29.50,https://www.discogs.com/release/210723,22.08
212,463062,b'Technologic',3.46,5.47,8.29,4.00,7.57,24.90,https://www.discogs.com/release/463062,19.25
...,...,...,...,...,...,...,...,...,...,...
187,1614916,b'Omen',4.61,5.63,19.99,5.00,5.35,6.90,https://www.discogs.com/release/1614916,-12.98
234,20688,b'Smack My Bitch Up',11.53,15.00,22.62,3.45,12.70,18.48,https://www.discogs.com/release/20688,-14.52
41,1058605,b'All Eyez On Me',20.75,29.05,99.99,19.67,24.38,69.69,https://www.discogs.com/release/1058605,-36.05
213,13861184,b'RTRN II JUNGLE',17.23,22.48,57.64,11.55,21.75,25.99,https://www.discogs.com/release/13861184,-38.06
5,6424917,b'Alive 2007',20.71,32.30,177.77,20.46,38.89,122.96,https://www.discogs.com/release/6424917,-48.47